; offsets.ini
; Обновляйте эти значения после каждого патча CS2
; Источник: a2x/cs2-dumper

LOCAL_PLAYER_PAWN=0x23C6268
ENTITY_LIST=0x2571220
PAWN_HANDLE=0x914
TEAM=0x3E7
HEALTH=0x34C
GAME_SCENE_NODE=0x330
ABS_ORIGIN=0xC8
EYE_ANGLES=0x3350